SistemaPV/Controllers/CBrandsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SistemaPV.Data;
using SistemaPV.Data.Entities;

namespace SistemaPV.Controllers
{
    [Authorize(Roles ="Admin, Manager")]
    public class CBrandsController : Controller
    {
        private readonly DataContext _context;

        public CBrandsController(DataContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            return View(await _context.Brands.ToListAsync());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cBrand = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cBrand == null)
            {
                return NotFound();
            }

            return View(cBrand);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CBrand cBrand)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cBrand);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cBrand);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cBrand = await _context.Brands.FindAsync(id);
            if (cBrand == null)
            {
                return NotFound();
            }
            return View(cBrand);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CBrand cBrand)
        {
            if (id != cBrand.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cBrand);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CBrandExists(cBrand.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cBrand);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cBrand = await _context.Brands
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cBrand == null)
            {
                return NotFound();
            }

            return View(cBrand);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cBrand = await _context.Brands.FindAsync(id);
            _context.Brands.Remove(cBrand);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CBrandExists(int id)
        {
            return _context.Brands.Any(e => e.Id == id);
        }
    }
}

SistemaPV/Controllers/CManagersController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPV.Data;
using SistemaPV.Data.Entities;
using SistemaPV.Helpers;
using SistemaPV.Models;

namespace SistemaPV.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CManagersController : Controller
    {
        private readonly DataContext dataContext;
        private readonly IUserHelper userHelper;

        public CManagersController(DataContext context, IUserHelper userHelper)
        {
            this.userHelper = userHelper; 
            dataContext = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await dataContext.Managers.Include(s => s.User).ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cManager = await dataContext.Managers
                .Include(p => p.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cManager == null)
            {
                return NotFound();
            }

            return View(cManager);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(addUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await userHelper.GetUserByIdAsync(model.User.Id);
                if (user == null)
                {
                    user = new CUser
                    {
                        FirstName = model.User.FirstName,
                        LastName = model.User.LastName,
                        Email = model.User.Email,
                        UserName = model.User.Email,
                        Area=model.User.Area
                    };
                }
                var result = await userHelper.AddUserAsync(user, model.Pass);
                if (result != IdentityResult.Success)
                {
                    throw new InvalidOperationException("No se ha podido añadir el usuario");
                }
                await userHelper.AddUserToRoleAsync(user, "Manager");
                var manager = new CManager
                {
                    Id = model.Id,
                    User = await dataContext.Users.FindAsync(user.Id)
                };
                dataContext.Add(manager);
                await dataContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cManager = await dataContext.Managers
                .Include(o => o.User)
                .FirstOrDefaultAsync(m => m.Id == id); ;
            if (cManager == null)
            {
                return NotFound();
            }
            return View(cManager);
        }

        /*
        [HttpPost]
        public async Task<IActionResult> Edit(addUserViewModel manager)
        {

            if (ModelState.IsValid)
            {
                var user = await this.dataContext.Users.FindAsync(manager.User.Id);

                user.Email = manager.User.Email;
                user.Area = manager.User.Area;
                try
                {
                    dataContext.Update(manager);
                    await dataContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CManagerExists(manager.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manager);
        }
        */

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, CManager manager)
        {
            if (id != manager.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    dataContext.Update(manager);
                    await dataContext.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CManagerExists(manager.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(manager);
        }

        private bool CManagerExists(int id)
        {
            return dataContext.Managers.Any(e => e.Id == id);
        }
    }
}

SistemaPV/Controllers/CSalesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaPV.Data;
using SistemaPV.Data.Entities;
using SistemaPV.Helpers;
using SistemaPV.Models;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace SistemaPV.Controllers
{
    [Authorize(Roles = "Admin, Manager, Salesman")]
    public class CSalesController : Controller
    {
        private readonly DataContext datacontext;
        private readonly IUserHelper userHelper;
        private readonly ICombosHelper combosHelper;


        public CSalesController(DataContext datacontext, IUserHelper userHelper, ICombosHelper combosHelper)
        {
            this.datacontext = datacontext;
            this.userHelper = userHelper;
            this.combosHelper = combosHelper;
        }

        public async Task<IActionResult> Index()
        {
            var user = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
            if (user == null)
            {
                return NotFound();
            }
            return View
                (
                this.datacontext.Sales.Include(o => o.Items)
                .ThenInclude(i => i.Product)
                .Where(o => o.User == user)
                );
        }

        public async Task<IActionResult> Create()
        {
            var user = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
            if (user == null)
            {
                return NotFound();
            }

            var saleDetailTemps = this.datacontext.SaleDetailTemps
                .Include(od => od.Product)
                .Where(od => od.User == user)
                .ToList();

            var saleTemp = new CSaleTemp
            {
                User = user,
                Items = saleDetailTemps,
                Date = null
            };

            return View(saleDetailTemps);
        }

        public IActionResult addProduct()
        {
            var model = new additemViewModel
            {
                Quantity = 1,
                Products = this.combosHelper.GetComboProducts()
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> addProduct(additemViewModel model)
        {
            if (this.ModelState.IsValid)
            {
                var user = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
                if (user == null)
                {
                    return NotFound();
                }
                var product = await this.datacontext.Products.FindAsync(model.ProductId);
                if (product == null)
                {
                    return NotFound();
                }
                var saleDetailTemp = await this.datacontext.SaleDetailTemps
                    .Where(pd => pd.User == user && pd.Product == product).FirstOrDefaultAsync();
                if (saleDetailTemp == null)
                {
                    saleDetailTemp = new CSaleDetailTemp
                    {
                        Product = product,
                        Quantity = model.Quantity,
                        UnitPrice = product.Price,
                        User = user
                    };
                    this.datacontext.SaleDetailTemps.Add(saleDetailTemp);
                }
                else
                {
                    saleDetailTemp.Quantity += model.Quantity;
                    this.datacontext.SaleDetailTemps.Update(saleDetailTemp);
                }
                await this.datacontext.SaveChangesAsync();
                return this.RedirectToAction("Create");
            }

            return this.View(model);
        }
        [Authorize(Roles = "Admin, Manager")]
        public async Task<IActionResult> deleteItem(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var saleDetailTemp = await this.datacontext.SaleDetailTemps.FindAsync(id);
            if (saleDetailTemp == null)
            {
                return NotFound();
            }
            this.datacontext.SaleDetailTemps.Remove(saleDetailTemp);
            await this.datacontext.SaveChangesAsync();
            return this.RedirectToAction("Create");
        }
        public async Task<IActionResult> increase(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var saleDetailTemp = await this.datacontext.SaleDetailTemps.FindAsync(id);
            if (saleDetailTemp == null)
            {
                return NotFound();
            }
            saleDetailTemp.Quantity += 1;
            this.datacontext.SaleDetailTemps.Update(saleDetailTemp);
            await this.datacontext.SaveChangesAsync();
            return this.RedirectToAction("Create");
        }
        public async Task<IActionResult> decrease(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var saleDetailTemp = await this.datacontext.SaleDetailTemps.FindAsync(id);
            if (saleDetailTemp == null)
            {
                return NotFound();
            }
            saleDetailTemp.Quantity -= 1;
            if (saleDetailTemp.Quantity >= 1)
            {

                this.datacontext.SaleDetailTemps.Update(saleDetailTemp);
                await this.datacontext.SaveChangesAsync();
            }
            return this.RedirectToAction("Create");
        }
        public IActionResult confirmOrder()
        {
            var model = new addSaleViewModel
            {
                PaidAmmount = 0,
                Items = this.combosHelper.GetComboItems()
            };

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> confirmOrder(addSaleViewModel model)
        {
            var user = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
            if (user == null)
            {
                return NotFound();
            }
            var sale = await this.datacontext.CSaleTemps
                .Include(pdt => pdt.Items)
                .FirstOrDefaultAsync(usr => usr.User == user);

            if (sale == null || sale.Items.Count == 0)
            {
                return NotFound();
            }

            var items = sale.Items.ToList();

            for (int i = 0; i < items.Count; i++)
            {
                this.datacontext.Products.Find(items[i].Product.Id).Quantity -= items[i].Quantity;
            }
            sale.PaidAmount = 1;

            await this.datacontext.SaveChangesAsync();
            return this.RedirectToAction("Edit", new { id = sale.Id });

        }

        public async Task<IActionResult> Edit(int? id)
        {
            var user = await this.userHelper.GetUserByEmailAsync(this.User.Identity.Name);
            if (user == null)
            {
                return NotFound();
            }

            if (id == null)
            {
                return NotFound();
            }

            var sale = await this.datacontext.Sales
                .FirstOrDefaultAsync(p => p.Id == id);
            if (sale == null)
            {
                return NotFound();
            }
            var model = new CSale
            {
                Id = sale.Id,
                Date = sale.Date,
                PaidAmount = sale.PaidAmount,
                User = user
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(CSale model)
        {
            if (ModelState.IsValid)
            {
                var sale = new CSale
                {
                    Id = model.Id,
                    Date = model.Date,
                    PaidAmount = model.PaidAmount
                };
                this.datacontext.Update(sale);
                await this.datacontext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(model);
        }
    }
}

SistemaPV/Views/Shared/NotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Esta es la página 404 xd</h1>

SistemaPV/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SistemaPV</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">

    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body id="body-pd">
    <header class="header" id="header">
        <div class="header_toggle" id="hamburguesa">
            <i class='bi bi-arrow-bar-right' id="header-toggle"></i>
        </div>
        <div >
            @if (this.User.Identity.IsAuthenticated)
            {
                <div>@this.User.Identity.Name</div>
                <div style="display:flex; justify-content:right; margin:0"><a asp-area="" asp-controller="Account" asp-action="Logout"><i class="bi bi-box-arrow-left nav_icon"></i>  Logout</a></div>

            }
            else
            {
                <div><a asp-area="" asp-controller="Account" asp-action="Login" >Login</a></div>
            }
            <!--<i class="bi bi-info-circle-fill"></i>-->
        </div>
    </header>
    <div class="l-navbar" id="nav-bar">
        <nav class="nav" style="color: #AFA5D9">
            <div>
                <a class="nav_logo nav_link active" asp-area="" asp-controller="Home" asp-action="Index">
                    <i class="bi bi-house-door-fill nav_logo-icon"></i>
                    <span class="nav_logo-name">SistemaPV</span>
                </a>
                <div class="nav_list">
                    @if (this.User.IsInRole("Salesman"))
                    {
                        <a class="nav_link" asp-area="" asp-controller="CProducts" asp-action="Index">
                            <i class="bi bi-box-seam nav_icon"></i>
                            <span class="nav_name">Productos</span>
                        </a>

                        <a class="nav_link" asp-area="" asp-controller="CSales" asp-action="Index">
                            <i class="bi bi-cart-plus"></i>
                            <span class="nav_name">Ventas</span>
                        </a>
                    }

                    @if (this.User.IsInRole("Manager"))
                    {
                        <a class="nav_link" asp-area="" asp-controller="CBrands" asp-action="Index">
                            <i class="bi bi-tags-fill nav_icon"></i>
                            <span class="nav_name">Marcas</span>
                        </a>
                        <a class="nav_link" asp-area="" asp-controller="CCategories" asp-action="Index">
                            <i class="bi bi-layers-fill nav_icon"></i>
                            <span class="nav_name">Categorías</span>
                        </a>
                        <a class="nav_link" asp-area="" asp-controller="CProducts" asp-action="Index">
                            <i class="bi bi-box-seam nav_icon"></i>
                            <span class="nav_name">Productos</span>
                        </a>

                        <a class="nav_link" asp-area="" asp-controller="CPurchases" asp-action="Index">
                            <i class="bi bi-bag"></i>
                            <span class="nav_name">Compras</span>
                        </a>

                        <a class="nav_link" asp-area="" asp-controller="CSales" asp-action="Index">
                            <i class="bi bi-cart-plus"></i>
                            <span class="nav_name">Ventas</span>
                        </a>

                        <a class="nav_link dropdown-button" style="margin:0">
                            <i class="bi bi-person-fill nav_icon"></i>
                            <span class="nav_name">Usuarios</span>
                        </a>
                        <div class="dropdown-container" style="display:none">
                            <a class="nav_link drop" style="margin:0" asp-area="" asp-controller="CSalesmen" asp-action="Index"><i class="bi bi-wallet2 nav_icon"></i>Vendedores</a>
                        </div>
                    }

                    @if (this.User.IsInRole("Admin"))
                    {
                        <a class="nav_link" asp-area="" asp-controller="CBrands" asp-action="Index">
                            <i class="bi bi-tags-fill nav_icon"></i>
                            <span class="nav_name">Marcas</span>
                        </a>
                        <a class="nav_link" asp-area="" asp-controller="CCategories" asp-action="Index">
                            <i class="bi bi-layers-fill nav_icon"></i>
                            <span class="nav_name">Categorías</span>
                        </a>
                        <a class="nav_link" asp-area="" asp-controller="CProducts" asp-action="Index">
                            <i class="bi bi-box-seam nav_icon"></i>
                            <span class="nav_name">Productos</span>
                        </a>
                        <a class="nav_link" asp-area="" asp-controller="CPurchases" asp-action="Index">
                            <i class="bi bi-bag"></i>
                            <span class="nav_name">Compras</span>
                        </a>
                        <a class="nav_link" asp-area="" asp-controller="CSales" asp-action="Index">
                            <i class="bi bi-cart-plus"></i>
                            <span class="nav_name">Ventas</span>
                        </a>
                        <a class="nav_link dropdown-button" style="margin:0">
                            <i class="bi bi-person-fill nav_icon"></i>
                            <span class="nav_name">Usuarios</span>
                        </a>

                        <div class="dropdown-container" style="display:none">
                            <a class="nav_link drop" style="margin:0" asp-area="" asp-controller="CManagers" asp-action="Index"><i class="bi bi-briefcase nav_icon"></i>Gerentes</a>
                            <a class="nav_link drop" style="margin:0" asp-area="" asp-controller="CSalesmen" asp-action="Index"><i class="bi bi-wallet2 nav_icon"></i>Vendedores</a>
                        </div>
                    }
                </div>
            </div> 
        </nav>
    </div>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/dropdown.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>